"""empty message

Revision ID: c6ba0b7c74ff
Revises: 42cd2f7cc868
Create Date: 2024-07-30 20:01:58.676219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ba0b7c74ff'
down_revision = '42cd2f7cc868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=500), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=500), nullable=True))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
